version: '3'
services:
  ${UI_CONTAINER_NAME}:
    container_name: ${UI_CONTAINER_NAME}
    restart: always
    image: ${UI_IMAGE}
    environment:
      TZ: Asia/Shanghai
    ports:
      - ${UI_PORT}:${UI_INTERNAL_PORT}
    volumes:
      - ./nginx-conf/${UI_CONTAINER_NAME}-nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: '${MAX_CPU}'
          memory: '${MAX_MEMORY}'
