version: '3'
services:
  # 主节点
  ${REDIS_MASTER_CONTAINER_NAME}:
    container_name: ${REDIS_MASTER_CONTAINER_NAME}
    restart: always
    image: ${REDIS_IMAGE}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${REDIS_MASTER_CONTAINER_NAME}-data:/data
      - ./redis-conf/${REDIS_MASTER_CONTAINER_NAME}.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: '${MAX_CPU}'
          memory: '${MAX_MEMORY}'

volumes:
  ${REDIS_MASTER_CONTAINER_NAME}-data:
